package clojure;

import clojure.lang.*;

public final class core_emit_defrecord_imap__5844 extends clojure.lang.AFunction {
 public static final clojure.lang.Var const__0;
 public static final java.lang.Object const__1;
 public static final java.lang.Object const__2;
 public static final clojure.lang.Var const__3;
 public static final clojure.lang.Symbol const__4;
 public static final clojure.lang.Var const__5;
 public static final clojure.lang.Var const__6;
 public static final clojure.lang.Var const__7;
 public static final clojure.lang.Symbol const__8;
 public static final clojure.lang.Var const__9;
 public static final clojure.lang.Var const__10;
 public static final clojure.lang.Symbol const__11;
 public static final clojure.lang.Symbol const__12;
 public static final clojure.lang.Var const__13;
 public static final clojure.lang.Symbol const__14;
 public static final clojure.lang.Symbol const__15;
 public static final clojure.lang.Symbol const__16;
 public static final clojure.lang.Symbol const__17;
 public static final clojure.lang.Symbol const__18;
 public static final clojure.lang.Symbol const__19;
 public static final clojure.lang.Symbol const__20;
 public static final clojure.lang.Var const__21;
 public static final clojure.lang.Symbol const__22;
 public static final clojure.lang.Symbol const__23;
 public static final clojure.lang.Symbol const__24;
 public static final clojure.lang.Symbol const__25;
 public static final clojure.lang.Symbol const__26;
 public static final clojure.lang.Symbol const__27;
 public static final clojure.lang.Symbol const__28;
 public static final clojure.lang.Symbol const__29;
 public static final clojure.lang.Symbol const__30;
 public static final clojure.lang.Symbol const__31;
 public static final clojure.lang.Symbol const__32;
 public static final clojure.lang.Symbol const__33;
 public static final clojure.lang.Symbol const__34;
 public static final clojure.lang.Symbol const__35;
 public static final clojure.lang.Symbol const__36;
 public static final clojure.lang.Var const__37;
 public static final clojure.lang.Keyword const__38;
 public static final clojure.lang.Symbol const__39;
 public static final clojure.lang.Var const__40;
 public static final clojure.lang.Symbol const__41;
 public static final clojure.lang.Symbol const__42;
 public static final clojure.lang.Symbol const__43;
 public static final clojure.lang.Symbol const__44;
 public static final clojure.lang.Symbol const__45;
 public static final clojure.lang.Symbol const__46;
 public static final clojure.lang.Symbol const__47;
 public static final clojure.lang.Symbol const__48;
 public static final clojure.lang.Symbol const__49;
 public static final clojure.lang.Symbol const__50;
 public static final clojure.lang.Symbol const__51;
 public static final clojure.lang.Symbol const__52;
 public static final clojure.lang.Symbol const__53;
 public static final clojure.lang.Symbol const__54;
 public static final clojure.lang.Symbol const__55;
 public static final clojure.lang.Symbol const__56;
 public static final clojure.lang.Symbol const__57;
 public static final clojure.lang.Symbol const__58;
 public static final clojure.lang.Symbol const__59;
 public static final clojure.lang.Symbol const__60;
 public static final clojure.lang.Symbol const__61;
 public static final clojure.lang.Symbol const__62;
 public static final clojure.lang.Symbol const__63;
 public static final clojure.lang.Symbol const__64;
 public static final clojure.lang.Symbol const__65;
 public static final clojure.lang.Symbol const__66;
 public static final clojure.lang.Symbol const__67;
 public static final clojure.lang.Symbol const__68;
 public static final clojure.lang.Symbol const__69;
 public static final clojure.lang.Symbol const__70;
 public static final clojure.lang.Symbol const__71;
 public static final clojure.lang.Symbol const__72;
 public static final clojure.lang.Symbol const__73;
 public static final clojure.lang.Var const__74;
 public static final clojure.lang.Symbol const__75;
 public static final clojure.lang.Var const__76;
 public static final clojure.lang.Symbol const__77;
 public static final clojure.lang.IPersistentSet const__78;
 public static final clojure.lang.Symbol const__79;
 public static final clojure.lang.Symbol const__80;
 public static final clojure.lang.Symbol const__81;
 public static final clojure.lang.Symbol const__82;
 public static final clojure.lang.Symbol const__83;
 public static final clojure.lang.Symbol const__84;
 public static final clojure.lang.Symbol const__85;
 public static final clojure.lang.Var const__86;
 public static final clojure.lang.Var const__87;
 public static final clojure.lang.Symbol const__88;
 public static final clojure.lang.Symbol const__89;
 public static final clojure.lang.Symbol const__90;
 public static final clojure.lang.Var const__91;
 public static final clojure.lang.Symbol const__92;
 public static final clojure.lang.Symbol const__93;
 public static final clojure.lang.Symbol const__94;
 public static final clojure.lang.IPersistentSet const__95;
 public static final clojure.lang.Symbol const__96;
 public static final clojure.lang.Symbol const__97;
 public static final clojure.lang.Symbol const__98;
 static {
  const__0 = (clojure.lang.Var)RT.var("clojure.core", "nth");
  const__1 = (java.lang.Object)0L;
  const__2 = (java.lang.Object)1L;
  const__3 = (clojure.lang.Var)RT.var("clojure.core", "conj");
  const__4 = (clojure.lang.Symbol)Symbol.intern(null, "clojure.lang.IPersistentMap");
  const__5 = (clojure.lang.Var)RT.var("clojure.core", "seq");
  const__6 = (clojure.lang.Var)RT.var("clojure.core", "concat");
  const__7 = (clojure.lang.Var)RT.var("clojure.core", "list");
  const__8 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "count");
  const__9 = (clojure.lang.Var)RT.var("clojure.core", "apply");
  const__10 = (clojure.lang.Var)RT.var("clojure.core", "vector");
  const__11 = (clojure.lang.Symbol)Symbol.intern(null, "this__5787__auto__");
  const__12 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "+");
  const__13 = (clojure.lang.Var)RT.var("clojure.core", "count");
  const__14 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "count");
  const__15 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__16 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "empty");
  const__17 = (clojure.lang.Symbol)Symbol.intern(null, "this__5788__auto__");
  const__18 = (clojure.lang.Symbol)Symbol.intern(null, "throw");
  const__19 = (clojure.lang.Symbol)Symbol.intern(null, "java.lang.UnsupportedOperationException.");
  const__20 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "str");
  const__21 = (clojure.lang.Var)RT.var("clojure.core", "str");
  const__22 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "cons");
  const__23 = (clojure.lang.Symbol)Symbol.intern(null, "this__5789__auto__");
  const__24 = (clojure.lang.Symbol)Symbol.intern(null, "e__5790__auto__");
  const__25 = (clojure.lang.Symbol)Symbol.intern(null, "var");
  const__26 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "imap-cons");
  const__27 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "equiv");
  const__28 = (clojure.lang.Symbol)Symbol.intern(null, "this__5791__auto__");
  const__29 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "boolean");
  const__30 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "or");
  const__31 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "identical?");
  const__32 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "when");
  const__33 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "identical?");
  const__34 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "class");
  const__35 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "class");
  const__36 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "let");
  const__37 = (clojure.lang.Var)RT.var("clojure.core", "with-meta");
  const__38 = (clojure.lang.Keyword)Keyword.intern(null, "tag");
  const__39 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "and");
  const__40 = (clojure.lang.Var)RT.var("clojure.core", "map");
  const__41 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "=");
  const__42 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__43 = (clojure.lang.Symbol)Symbol.intern(null, ".");
  const__44 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__45 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "containsKey");
  const__46 = (clojure.lang.Symbol)Symbol.intern(null, "this__5792__auto__");
  const__47 = (clojure.lang.Symbol)Symbol.intern(null, "k__5793__auto__");
  const__48 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "not");
  const__49 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "identical?");
  const__50 = (clojure.lang.Symbol)Symbol.intern(null, ".valAt");
  const__51 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "entryAt");
  const__52 = (clojure.lang.Symbol)Symbol.intern(null, "this__5794__auto__");
  const__53 = (clojure.lang.Symbol)Symbol.intern(null, "k__5795__auto__");
  const__54 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "let");
  const__55 = (clojure.lang.Symbol)Symbol.intern(null, "v__5796__auto__");
  const__56 = (clojure.lang.Symbol)Symbol.intern(null, ".valAt");
  const__57 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "when-not");
  const__58 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "identical?");
  const__59 = (clojure.lang.Symbol)Symbol.intern(null, "clojure.lang.MapEntry.");
  const__60 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "seq");
  const__61 = (clojure.lang.Symbol)Symbol.intern(null, "this__5798__auto__");
  const__62 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "seq");
  const__63 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "concat");
  const__64 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__65 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "iterator");
  const__66 = (clojure.lang.Symbol)Symbol.intern(null, "this__5799__auto__");
  const__67 = (clojure.lang.Symbol)Symbol.intern(null, "clojure.lang.SeqIterator.");
  const__68 = (clojure.lang.Symbol)Symbol.intern(null, ".seq");
  const__69 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "assoc");
  const__70 = (clojure.lang.Symbol)Symbol.intern(null, "this__5800__auto__");
  const__71 = (clojure.lang.Symbol)Symbol.intern(null, "k__5801__auto__");
  const__72 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "condp");
  const__73 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "identical?");
  const__74 = (clojure.lang.Var)RT.var("clojure.core", "mapcat");
  const__75 = (clojure.lang.Symbol)Symbol.intern(null, "new");
  const__76 = (clojure.lang.Var)RT.var("clojure.core", "remove");
  const__77 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__78 = (clojure.lang.IPersistentSet)PersistentHashSet.create(Symbol.intern(null, "__extmap"));
  const__79 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "assoc");
  const__80 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__81 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "without");
  const__82 = (clojure.lang.Symbol)Symbol.intern(null, "this__5802__auto__");
  const__83 = (clojure.lang.Symbol)Symbol.intern(null, "k__5803__auto__");
  const__84 = (clojure.lang.Symbol)Symbol.intern(null, "if");
  const__85 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "contains?");
  const__86 = (clojure.lang.Var)RT.var("clojure.core", "hash-set");
  const__87 = (clojure.lang.Var)RT.var("clojure.core", "keyword");
  const__88 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "dissoc");
  const__89 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "with-meta");
  const__90 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "into");
  const__91 = (clojure.lang.Var)RT.var("clojure.core", "hash-map");
  const__92 = (clojure.lang.Symbol)Symbol.intern(null, "__meta");
  const__93 = (clojure.lang.Symbol)Symbol.intern(null, "new");
  const__94 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
  const__95 = (clojure.lang.IPersistentSet)PersistentHashSet.create(Symbol.intern(null, "__extmap"));
  const__96 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "not-empty");
  const__97 = (clojure.lang.Symbol)Symbol.intern("clojure.core", "dissoc");
  const__98 = (clojure.lang.Symbol)Symbol.intern(null, "__extmap");
 }
 Object tagname1;
 Object base_fields12;
 Object fields13;
 Object gs15;
 Object classname6;
 public core_emit_defrecord_imap__5844(final Object tagname1, final Object base_fields12, final Object fields13, final Object gs15, final Object classname6) {
  super();
  this.tagname1 = tagname1;
  this.base_fields12 = base_fields12;
  this.fields13 = fields13;
  this.gs15 = gs15;
  this.classname6 = classname6;
 }
 public java.lang.Object invoke(java.lang.Object p__58431) {
  {
   Object vec__58452 = p__58431;
   Object i3 = ((java.lang.Object)clojure.lang.RT.nth(((java.lang.Object)vec__58452), (int)RT.intCast(0L), ((java.lang.Object)null)));
   Object m4 = ((java.lang.Object)clojure.lang.RT.nth(((java.lang.Object)vec__58452), (int)RT.intCast(1L), ((java.lang.Object)null)));
   return RT.vector(((IFn)const__3.getRawRoot()).invoke(i3, const__4), ((IFn)const__3.getRawRoot()).invoke(m4, ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__8), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__11))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__12), ((IFn)const__7.getRawRoot()).invoke(Integer.valueOf(clojure.lang.RT.count(((java.lang.Object)this.base_fields12)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__14), ((IFn)const__7.getRawRoot()).invoke(const__15))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__16), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__17))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__18), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__19), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__20), ((IFn)const__7.getRawRoot()).invoke("Can't create empty: "), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__21.getRawRoot()).invoke(this.classname6))))))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__22), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__23), ((IFn)const__7.getRawRoot()).invoke(const__24))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__25), ((IFn)const__7.getRawRoot()).invoke(const__26)))), ((IFn)const__7.getRawRoot()).invoke(const__23), ((IFn)const__7.getRawRoot()).invoke(const__24)))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__27), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__28), ((IFn)const__7.getRawRoot()).invoke(this.gs15))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__29), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__30), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__31), ((IFn)const__7.getRawRoot()).invoke(const__28), ((IFn)const__7.getRawRoot()).invoke(this.gs15)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__32), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__33), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__34), ((IFn)const__7.getRawRoot()).invoke(const__28)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__35), ((IFn)const__7.getRawRoot()).invoke(this.gs15))))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__36), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(this.gs15), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__37.getRawRoot()).invoke(this.gs15, RT.mapUniqueKeys(const__38, this.tagname1))))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__39), ((IFn)const__40.getRawRoot()).invoke(new clojure.core_emit_defrecord_imap__5844_fn__5846(this.gs15), this.base_fields12), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__41), ((IFn)const__7.getRawRoot()).invoke(const__42), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__43), ((IFn)const__7.getRawRoot()).invoke(this.gs15), ((IFn)const__7.getRawRoot()).invoke(const__44)))))))))))))))))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__45), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__46), ((IFn)const__7.getRawRoot()).invoke(const__47))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__48), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__49), ((IFn)const__7.getRawRoot()).invoke(const__46), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__50), ((IFn)const__7.getRawRoot()).invoke(const__46), ((IFn)const__7.getRawRoot()).invoke(const__47), ((IFn)const__7.getRawRoot()).invoke(const__46)))))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__51), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__52), ((IFn)const__7.getRawRoot()).invoke(const__53))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__54), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__55), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__56), ((IFn)const__7.getRawRoot()).invoke(const__52), ((IFn)const__7.getRawRoot()).invoke(const__53), ((IFn)const__7.getRawRoot()).invoke(const__52)))))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__57), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__58), ((IFn)const__7.getRawRoot()).invoke(const__52), ((IFn)const__7.getRawRoot()).invoke(const__55)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__59), ((IFn)const__7.getRawRoot()).invoke(const__53), ((IFn)const__7.getRawRoot()).invoke(const__55)))))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__60), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__61))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__62), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__63), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__40.getRawRoot()).invoke(new clojure.core_emit_defrecord_imap__5844_fn__5848(), this.base_fields12))))), ((IFn)const__7.getRawRoot()).invoke(const__64))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__65), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__66))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__67), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__68), ((IFn)const__7.getRawRoot()).invoke(const__66))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__69), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__70), ((IFn)const__7.getRawRoot()).invoke(const__71), ((IFn)const__7.getRawRoot()).invoke(this.gs15))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__72), ((IFn)const__7.getRawRoot()).invoke(const__73), ((IFn)const__7.getRawRoot()).invoke(const__71), ((IFn)const__74.getRawRoot()).invoke(new clojure.core_emit_defrecord_imap__5844_fn__5850(this.tagname1, this.fields13, this.gs15), this.base_fields12), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__75), ((IFn)const__7.getRawRoot()).invoke(this.tagname1), ((IFn)const__76.getRawRoot()).invoke(const__78, this.fields13), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__79), ((IFn)const__7.getRawRoot()).invoke(const__80), ((IFn)const__7.getRawRoot()).invoke(const__71), ((IFn)const__7.getRawRoot()).invoke(this.gs15)))))))))))), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__81), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__10.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__82), ((IFn)const__7.getRawRoot()).invoke(const__83))))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__84), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__85), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__86.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__40.getRawRoot()).invoke(const__87.getRawRoot(), this.base_fields12))))), ((IFn)const__7.getRawRoot()).invoke(const__83)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__88), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__89), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__90), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__9.getRawRoot()).invoke(const__91.getRawRoot(), ((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke()))), ((IFn)const__7.getRawRoot()).invoke(const__82)))), ((IFn)const__7.getRawRoot()).invoke(const__92)))), ((IFn)const__7.getRawRoot()).invoke(const__83)))), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__93), ((IFn)const__7.getRawRoot()).invoke(this.tagname1), ((IFn)const__76.getRawRoot()).invoke(const__95, this.fields13), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__96), ((IFn)const__7.getRawRoot()).invoke(((IFn)const__5.getRawRoot()).invoke(((IFn)const__6.getRawRoot()).invoke(((IFn)const__7.getRawRoot()).invoke(const__97), ((IFn)const__7.getRawRoot()).invoke(const__98), ((IFn)const__7.getRawRoot()).invoke(const__83)))))))))))))))));
  }
 }
}
